import {useEffect,useRef,useState} from 'react';
import {OrderStatus} from './OrderStatus';
import {deliveryRequest,DeliveryRequestError} from './DeliveryWorkspace';
import {ComparisonResults,type ComparisonModel} from './ComparisonResults';

type Preview={source_hash:string;format:string;sheets:{name:string;max_row:number;max_col:number;preview:{row:number;cells:{column:string;type:string;value:unknown}[]}[]}[]};
type Mapping={sheet:string;range:string;header:string;keys:string;amount:string;period:string;meaning:string;exclusions:string};
type SavedMapping={sheet:string;range:string;header_row:number;key_columns:string[];amount_column:string;exclusions:{row:number;reason:string}[];criteria:{period:string;amount_meaning:string}};
export type ComparisonJob={order_id?:string|null;entitlement_active?:boolean;job_id:string;revision:number;status:string;expires_at:number;source_pair_hash:string;sources:Record<string,Preview>;internal_rehearsal:boolean;comparison_spec?:{A:SavedMapping;B:SavedMapping;policy:{tolerance_krw:string}};spec_hash?:string;preflight?:{eligibility:string;input_rows:Record<string,number>;excluded_rows:Record<string,number>;input_issues:{source:string;sheet:string;row:number;reason_codes:string[]}[];duplicate_locations:{source:string;sheet:string;rows:number[]}[];comparable_pair_count:number;limits_confirmed_required:boolean};result?:ComparisonModel;delivery?:{delivery_id:string;files:Record<string,{bytes:number}>;expires_at:number}};
const remembered='workbookcare:comparison:last-job';
const defaults:Mapping={sheet:'',range:'',header:'1',keys:'A',amount:'B',period:'',meaning:'',exclusions:''};
const labels:Record<string,string>={COMPARISON_REPORT_XLSX:'비교 보고서 XLSX',COMPARISON_VERIFICATION_HTML:'비교 재검증 HTML'};
const base64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));reader.readAsDataURL(file);});
export function ComparisonWorkspace({open,onOpen,initialJob}:{open:boolean;onOpen:()=>void;initialJob?:ComparisonJob}){
 const [files,setFiles]=useState<Record<string,File|null>>({A:null,B:null});const [consent,setConsent]=useState(false);const [job,setJob]=useState<ComparisonJob|null>(initialJob??null);
 const [mapping,setMapping]=useState<Record<string,Mapping>>({A:{...defaults},B:{...defaults}});const [tolerance,setTolerance]=useState('0');const [confirmed,setConfirmed]=useState(false);const [limited,setLimited]=useState(false);const [dirty,setDirty]=useState(false);
 const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const heading=useRef<HTMLHeadingElement>(null);const resumed=useRef(false);
 useEffect(()=>{if(open){heading.current?.focus();heading.current?.scrollIntoView({block:'start'});}},[open]);
 useEffect(()=>{if(job)try{localStorage.setItem(remembered,JSON.stringify({job_id:job.job_id,expires_at:job.expires_at}));}catch{/* Local history is optional. */}},[job]);
 useEffect(()=>{if(initialJob){resumed.current=true;setJob(initialJob);const next=initialJob;if(next.comparison_spec){setMapping(Object.fromEntries((["A","B"] as const).map(side=>{const m=next.comparison_spec![side];return [side,{sheet:m.sheet,range:m.range,header:String(m.header_row),keys:m.key_columns.join(","),amount:m.amount_column,period:m.criteria.period,meaning:m.criteria.amount_meaning,exclusions:m.exclusions.map(e=>`${e.row}: ${e.reason}`).join("\n")}]})));setTolerance(next.comparison_spec.policy.tolerance_krw);} }},[initialJob]);
 useEffect(()=>{if(!open||resumed.current)return;resumed.current=true;try{const saved=JSON.parse(localStorage.getItem(remembered)??'null');if(saved&&saved.expires_at*1000>Date.now())deliveryRequest<ComparisonJob>({action:'get',job_id:saved.job_id}).then(next=>{setJob(next);if(next.comparison_spec){setMapping(Object.fromEntries((["A","B"] as const).map(side=>{const m=next.comparison_spec![side];return [side,{sheet:m.sheet,range:m.range,header:String(m.header_row),keys:m.key_columns.join(","),amount:m.amount_column,period:m.criteria.period,meaning:m.criteria.amount_meaning,exclusions:m.exclusions.map(e=>`${e.row}: ${e.reason}`).join("\n")}]})));setTolerance(next.comparison_spec.policy.tolerance_krw);}}).catch(()=>setError('이전 비교 작업이 만료되었거나 이 브라우저의 작업이 아닙니다. 새 자료로 시작하세요.'));}catch{/* No stored workbook content is read. */}},[open]);
 useEffect(()=>{if(!job||!['RUNNING','CANCEL_REQUESTED'].includes(job.status))return;const c=new AbortController();const timer=setInterval(()=>deliveryRequest<ComparisonJob>({action:'get',job_id:job.job_id},c.signal).then(setJob).catch(()=>{}),1000);return()=>{clearInterval(timer);c.abort();};},[job?.job_id,job?.status]);
 const expire=()=>{setJob(null);setFiles({A:null,B:null});setConsent(false);setConfirmed(false);setLimited(false);setError('비교 원본 보관이 만료되었습니다. 기존 주문에서 복구 또는 취소를 선택하세요.');try{localStorage.removeItem(remembered)}catch{/* Optional history. */}};
 useEffect(()=>{if(!job)return;const timer=setTimeout(expire,Math.max(0,job.expires_at*1000-Date.now()));return()=>clearTimeout(timer)},[job?.job_id,job?.expires_at]);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work();}catch(e){if(e instanceof DeliveryRequestError&&['INPUT_EXPIRED','JOB_NOT_FOUND'].includes(e.code)){expire();return;}setError(e instanceof Error?e.message:'비교를 완료하지 못했습니다.');if(job)try{setJob(await deliveryRequest<ComparisonJob>({action:'get',job_id:job.job_id}));}catch{/* Preserve the original error. */}}finally{setBusy(false);}};
 const edit=(side:string,key:keyof Mapping,value:string)=>{setMapping(old=>({...old,[side]:{...old[side],[key]:value}}));setConfirmed(false);setDirty(true);setLimited(false);};
 const upload=()=>run(async()=>{
  if(!files.A||!files.B||!consent)throw new Error('두 파일과 합성 자료 동의를 확인하세요.');
  if(files.A.size>2*1024**2||files.B.size>2*1024**2)throw new Error('현재 비교 베타는 파일당 2MiB 이하입니다.');
  const sources={A:{filename:files.A.name,file_base64:await base64(files.A)},B:{filename:files.B.name,file_base64:await base64(files.B)}};
  const next=await deliveryRequest<ComparisonJob>({action:'create_comparison',sources,consent:true,request_key:crypto.randomUUID()});setJob(next);
  setMapping(Object.fromEntries(['A','B'].map(side=>{const sheet=next.sources[side].sheets[0];return [side,{...defaults,sheet:sheet.name,range:`A1:B${Math.max(2,Math.min(sheet.max_row,20001))}`}];})));setDirty(false);
 });
 const prepare=()=>run(async()=>{
  if(!job)return;const selected:Record<string,object>={};
  for(const side of ['A','B']){const m=mapping[side];const exclusions=m.exclusions.split('\n').filter(s=>s.trim()).map(line=>{const match=/^\s*(\d+)\s*:\s*(.+)$/.exec(line);if(!match)throw new Error('제외 행은 “7: 합계행”처럼 한 줄에 하나씩 입력하세요.');return {row:Number(match[1]),reason:match[2]};});selected[side]={sheet:m.sheet,range:m.range.toUpperCase(),header_row:Number(m.header),key_columns:m.keys.split(',').map(s=>s.trim().toUpperCase()),amount_column:m.amount.toUpperCase(),exclusions,criteria:{period:m.period,amount_meaning:m.meaning,currency:'KRW',unit:'KRW_WON'}};}
  if(mapping.A.period!==mapping.B.period||mapping.A.meaning!==mapping.B.meaning)throw new Error('A/B의 기간과 금액 의미가 다릅니다. 같은 기준의 자료만 비교할 수 있습니다.');
  const next=await deliveryRequest<ComparisonJob>({action:'prepare_comparison',job_id:job.job_id,revision:job.revision,source_pair_hash:job.source_pair_hash,spec:{...selected,policy:{confirmed,currency:'KRW',unit:'KRW_WON',period:mapping.A.period,amount_meaning:mapping.A.meaning,normalization:'NONE',tolerance_krw:tolerance}}});setJob(next);setDirty(false);setLimited(false);
 });
 const download=(kind:string)=>run(async()=>{if(!job)return;const file=await deliveryRequest<{filename:string;mime:string;file_base64:string}>({action:'comparison_download',job_id:job.job_id,kind});const data=Uint8Array.from(atob(file.file_base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([data],{type:file.mime}));const a=document.createElement('a');a.href=url;a.download=file.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const reset=()=>{setJob(null);setFiles({A:null,B:null});setConsent(false);setConfirmed(false);setMapping({A:{...defaults},B:{...defaults}});setError(null);setDirty(false);setLimited(false);try{localStorage.removeItem(remembered);}catch{/* Optional opaque history. */}};
 if(!open)return <section className="comparison-entry shell"><h2>두 파일의 차이를 함께 확인하세요</h2><p>같은 거래번호의 금액과 한쪽 자료에만 있는 항목을 비교합니다. A/B 원본을 바꾸지 않는 별도 보고서입니다.</p><button type="button" className="button button--outline" onClick={onOpen}>두 파일 비교 사전 확인</button></section>;
 const locked=busy||job?.entitlement_active||job?.internal_rehearsal||job?.status==='READY';const active=job&&['RUNNING','CANCEL_REQUESTED'].includes(job.status);
 return <section id="comparison-workspace" className="comparison-workspace shell" aria-label="두 파일 비교 작업"><h2 ref={heading} tabIndex={-1}>두 파일 비교</h2><p>원본 미변경 · 같은 문자 거래번호와 정수 KRW 금액을 비교합니다. B는 정답 자료가 아닙니다.</p><p className="delivery-beta-note">합성 검증 베타 · 일반 구매 준비 중 · 파일당 2MiB / 선택 20,000행·50열·250,000셀 이하 · 작업 15분 보관. 서버 재시작 시 사라질 수 있습니다.</p>
 {!job?<><div className="comparison-inputs">{['A','B'].map(side=><label className="comparison-file" key={side}><strong>자료 {side}</strong><span>{files[side]?.name??'선택한 파일 없음'}</span><input type="file" accept=".xlsx,.csv" aria-label={`비교할 ${side} 파일`} onChange={e=>setFiles(old=>({...old,[side]:e.target.files?.[0]??null}))}/></label>)}</div><label className="delivery-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>두 파일은 업로드 권한이 있는 합성 자료이며 비교와 임시 보관에 동의합니다.</label><button type="button" className="button button--primary" disabled={busy||!files.A||!files.B||!consent} onClick={upload}>두 원본 고정하고 기준 선택</button></>
 : <><p>두 원본 고정 완료 · 수정하지 않음</p>{job.status!=='READY'&&<details className="comparison-criteria" open={!job.preflight||dirty}><summary>선택한 비교 범위와 기준 확인</summary><div className="comparison-inputs">{['A','B'].map(side=><fieldset key={side} className="comparison-mapping" disabled={locked}><legend>자료 {side} · {files[side]?.name??job.sources[side].format+' 고정본'}</legend><label>시트<select aria-label={`${side} 시트`} value={mapping[side].sheet} onChange={e=>edit(side,'sheet',e.target.value)}>{job.sources[side].sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label>
  <details><summary>원본의 최소 행 미리보기</summary>{job.sources[side].sheets.filter(s=>s.name===mapping[side].sheet).map(s=><div className="comparison-preview" key={s.name}>{s.preview.map(r=><p key={r.row}>{r.row}행 · {r.cells.map(c=>`${c.column}: ${String(c.value??'빈 셀')}`).join(' / ')}</p>)}</div>)}</details>
  <label>표 범위<input aria-label={`${side} 표 범위`} value={mapping[side].range} onChange={e=>edit(side,'range',e.target.value)}/></label><label>헤더행<input aria-label={`${side} 헤더행`} type="number" min="1" value={mapping[side].header} onChange={e=>edit(side,'header',e.target.value)}/></label><label>거래번호 열 · 최대 3개<input aria-label={`${side} 거래번호 열`} value={mapping[side].keys} onChange={e=>edit(side,'keys',e.target.value)}/></label><label>금액 열<input aria-label={`${side} 금액 열`} value={mapping[side].amount} onChange={e=>edit(side,'amount',e.target.value)}/></label>
  <label>기간 또는 기준시점<input aria-label={`${side} 비교 기간`} value={mapping[side].period} onChange={e=>edit(side,'period',e.target.value)} placeholder="예: 2026년 9월"/></label><label>금액의 의미<input aria-label={`${side} 금액 의미`} value={mapping[side].meaning} onChange={e=>edit(side,'meaning',e.target.value)} placeholder="예: 부가세 포함 총액"/></label><details><summary>명시적으로 제외할 행</summary><label>행 번호와 사유<textarea aria-label={`${side} 제외 행`} value={mapping[side].exclusions} onChange={e=>edit(side,'exclusions',e.target.value)} placeholder="7: 별도 합계행"/></label></details></fieldset>)}</div>
  <fieldset className="comparison-policy" disabled={locked}><label>허용오차 · 원<input aria-label="비교 허용오차" inputMode="numeric" value={tolerance} onChange={e=>{setTolerance(e.target.value);setConfirmed(false);setDirty(true);}}/></label><p>키는 문자 그대로 비교합니다. 선행 0·대소문자·공백을 임의로 바꾸지 않습니다. 숨김·필터행도 선택 범위 안이면 포함합니다.</p><label className="delivery-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>두 자료의 기간·금액 의미와 KRW 원 단위가 같고, 선택한 헤더·키·금액 열이 맞음을 확인합니다.</label><button type="button" className="button button--primary" disabled={!confirmed||busy} onClick={prepare}>비교 가능 범위 확인</button></fieldset></details>}
  {dirty&&job.preflight&&<p role="status">기준을 변경했습니다. 새 범위를 확인해야 합니다.</p>}
  {job.preflight&&!dirty&&job.status!=='READY'&&<section className="comparison-preflight" aria-label="비교 사전 확인 결과"><h3>{job.preflight.eligibility==='NOT_ELIGIBLE'?'현재 기준에서는 비교할 수 없습니다':job.preflight.eligibility==='ELIGIBLE_WITH_LIMITATIONS'?'비교 가능 · 보류할 자료 확인 필요':'비교 범위 확인 완료'}</h3><p>A 선택 {job.preflight.input_rows.A}행 · B 선택 {job.preflight.input_rows.B}행 · 비교 가능한 공통 1:1 키 {job.preflight.comparable_pair_count}개</p><p>원천 자료오류 {job.preflight.input_issues.length}행 · 원천별 중복 {job.preflight.duplicate_locations.length}묶음</p>
   <details><summary>무료로 확인하는 입력 오류·중복 위치</summary><ul>{job.preflight.input_issues.map((r,i)=><li key={i}>{r.source} · {r.sheet} {r.row}행 · {r.reason_codes.map(c=>c==='INVALID_KEY'?'문자 키 확인 필요':'정수 금액 확인 필요').join(', ')}</li>)}{job.preflight.duplicate_locations.map((r,i)=><li key={'d'+i}>{r.source} · {r.sheet} {r.rows.join(', ')}행 · 중복 키</li>)}</ul></details>
   {job.preflight.limits_confirmed_required&&<label className="delivery-check"><input type="checkbox" checked={limited} onChange={e=>setLimited(e.target.checked)}/>중복·자료오류는 보류하고 모든 원천 행을 보고서에 남기는 제한을 확인했습니다.</label>}
   <p>일반 구매는 아직 준비 중입니다. 내부 합성 검증권은 실제 결제나 수정 사용권이 아닙니다.</p>{(job.internal_rehearsal||job.entitlement_active)&&job.preflight.eligibility!=='NOT_ELIGIBLE'&&<button type="button" className="button button--primary" disabled={busy||(job.preflight.limits_confirmed_required&&!limited)} onClick={()=>run(async()=>{setJob({...job,status:'RUNNING'});setJob(await deliveryRequest<ComparisonJob>({action:'execute_comparison',job_id:job.job_id,acknowledge_limitations:limited}));})}>비교 보고서 만들기</button>}
  </section>}
  {job.preflight&&!dirty&&job.status!=='READY'&&<OrderStatus job={job} limitsConfirmed={limited||!job.preflight.limits_confirmed_required} onRefresh={async()=>setJob(await deliveryRequest<ComparisonJob>({action:'get',job_id:job.job_id}))}/>}
  {active&&<div role="status"><p>{job.status==='CANCEL_REQUESTED'?'취소 요청됨 · 프로세스 종료와 정리 중':'두 자료의 전체 결과와 보고서를 검증 중입니다.'}</p><button type="button" className="button button--outline" disabled={job.status==='CANCEL_REQUESTED'} onClick={()=>run(async()=>setJob(await deliveryRequest<ComparisonJob>({action:'cancel',job_id:job.job_id})))}>비교 실행 취소</button></div>}
  {job.status==='QUARANTINED'&&<p role="alert">전체 검증을 완료하지 못해 보고서를 격리했습니다. 일부 결과를 완성본으로 제공하지 않습니다.</p>}
  {job.status==='CANCELLED'&&<p role="status">취소 완료 · 보고서를 게시하지 않았습니다.</p>}
  {job.status==='READY'&&job.result&&job.delivery&&<><div className="delivery-ready"><h3>비교 보고서 두 파일이 준비되었습니다</h3><p>수정본이 포함되지 않는 검토 보고서입니다. 같은 작업의 재다운로드에는 추가 결제가 없습니다.</p><div className="delivery-downloads">{Object.keys(job.delivery.files).map(kind=><button type="button" key={kind} className="button button--outline" disabled={busy} onClick={()=>download(kind)}>{labels[kind]} 받기</button>)}</div><p>보관 만료: {new Date(job.delivery.expires_at*1000).toLocaleString('ko-KR')}</p></div><ComparisonResults key={job.spec_hash} model={job.result}/></>}
  <div className="delivery-actions"><button type="button" className="button button--outline" disabled={busy} onClick={()=>run(async()=>setJob(await deliveryRequest<ComparisonJob>({action:'get',job_id:job.job_id})))}>비교 작업 상태 확인</button><button type="button" className="button button--outline" disabled={busy} onClick={reset}>다음 기간·새 자료 비교</button><button type="button" className="button button--ghost" disabled={busy} onClick={()=>run(async()=>{const next=await deliveryRequest<ComparisonJob|{status:'DELETED'}>({action:'delete',job_id:job.job_id});if(next.status==='DELETED')reset();else setJob(next as ComparisonJob);})}>비교 원본과 결과 삭제</button></div>
 </>}{busy&&!active&&<p role="status">두 자료를 안전하게 처리 중입니다…</p>}{error&&<p role="alert">{error}</p>}</section>;
}
